# Generated by Django 3.0.3 on 2020-02-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x',
            new_name='size_x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y',
            new_name='size_y',
        ),
    ]
