# Generated by Django 3.0.3 on 2020-02-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='y',
        ),
    ]
